/*** JS 1 ***/
function whenExists(elements, callback) {
	elements = elements.split(',');
	var interval = setInterval(function () {
		for (var i = 0; i < elements.length; i++) {
			if (document.querySelectorAll(elements[i]).length) {
				elements.splice(i, 1);
				i--;
			}
		}
		if (elements.length === 0) {
			callback();
			clearInterval(interval);
		}
	}, 100);
}
whenExists('#mainimage', function () {

	$('<div class="da_new-section da_desktop"><div class="da_header"><h2>Why Choose Coinigy?</h2><h6>We offer a variety of features that make us different</h6></div><div class="da_section-content"><div class="da_section-text"><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/45.png"/></div><div class="da_description-text"><h6>Trade on 45+ Exchanges</h6><p>We offer access to more than 40 exchanges. Coinigy’s connectivity across the cryptocurrency universe enables the firm to provide real-time access to pricing data, full-featured spot trading, Arbitrage Matrix and portfolio management/aggregation tools.</p></div></div><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/247.png"/></div><div class="da_description-text"><h6>24/7 Exchange and Wallet Portfolio Monitoring</h6><p>Coinigy is your one-stop-shop for your portfolio management. We offer SMS & email price and trade alerts to help you stay ahead of the game. Coinigy OS, the ultimate anti-theft device for crypto because you can monitor all your exchanges and wallets in one place.</p></div></div><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/nowithdraw.png"/></div><div class="da_description-text"><h6>No Withdraw Limits</h6><p>We do not charge any fees for use of our platform, not do we implement any withdrawal limits. We only charge you based on the subscription you would sign up for after your trial period has expired.</p></div></div><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/apps.png"/></div><div class="da_description-text"><h6>Apps and Third-Party Integrations and Alerts</h6><p>Coinigy is the most comprehensive bitcoin and cryptocurrency trading and portfolio tool available. With extensive charting tools and real-time market data, no other cryptocurrency app can match Coinigy in its scope, detail, and performance.</p></div></div></div><div class="da_section-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/Chart.jpg"/><a class="da_cta" href="https://www.coinigy.com/features/">LEARN MORE</a></div></div></div>').appendTo('#mainimage');


	$('<div class="da_new-section da_mobile"><div class="da_header"><h2>Why Choose Coinigy?</h2><h6>We offer a variety of features that make us different</h6></div><div class="da_section-content"><div class="da_section-text"><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/45.png"/></div><div class="da_description-text"><h6>Trade on 45+ Exchanges</h6><p>We offer access to more than 40 exchanges. Coinigy’s connectivity across the cryptocurrency universe enables the firm to provide real-time access to pricing data, full-featured spot trading, Arbitrage Matrix and portfolio management/aggregation tools.</p></div></div><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/247.png"/></div><div class="da_description-text"><h6>24/7 Exchange and Wallet Portfolio Monitoring</h6><p>Coinigy is your one-stop-shop for your portfolio management. We offer SMS & email price and trade alerts to help you stay ahead of the game. Coinigy OS, the ultimate anti-theft device for crypto because you can monitor all your exchanges and wallets in one place.</p></div></div><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/nowithdraw.png"/></div><div class="da_description-text"><h6>No Withdraw Limits</h6><p>We do not charge any fees for use of our platform, not do we implement any withdrawal limits. We only charge you based on the subscription you would sign up for after your trial period has expired.</p></div></div><div class="da_description"><div class="da_description-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/apps.png"/></div><div class="da_description-text"><h6>Apps and Third-Party Integrations and Alerts</h6><p>Coinigy is the most comprehensive bitcoin and cryptocurrency trading and portfolio tool available. With extensive charting tools and real-time market data, no other cryptocurrency app can match Coinigy in its scope, detail, and performance.</p></div></div></div><div class="da_section-img"><img src="https://s3-us-west-1.amazonaws.com/static.disruptive.co/coinigy/homepage-features/Chart.jpg"/><a class="da_cta" href="https://www.coinigy.com/features/">LEARN MORE</a></div></div></div>').insertBefore('#mainimage h3');
});
