name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Shopify
      uses: pgrimaud/action-shopify@2.1.0
      env:
        SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        SHOPIFY_THEME_ID: 11137515543
        THEME_PATH: ./src
      with:
        args: --ignored-file=config/settings_data.json
